### ISSUE TITLE
create barrier sprites

### ISSUE THREAD

**Issue by bmvcbr** [KSU-SE-2022-TeamPlusPlus/VideoGame#13]
![Untitled](https://user-images.githubusercontent.com/50416928/153973189-fd522cdc-4364-4d8e-9262-3e3f71ccbbf5.png)

**Comment by jmaus06** [comment]
Found a wall sprite and modified and resized it. Uploaded to github, put basic barrier.js file in repo

**Comment by jmaus06** [comment]
added lawn chair sprite to repo

**Comment by bmvcbr** [comment]
Add picnic table graphic, maybe take up two lanes instead of one
