### ISSUE TITLE
Create a "distance rolled" score on the screen

### ISSUE THREAD

**Issue by bmvcbr** [KSU-SE-2022-TeamPlusPlus/VideoGame#22]
There should be a number at the top counting some sort of measurement to show how far the basketball has rolled on the screen (think of the chrome dinosaur game)

**Comment by Spheniski** [comment]
To be added to Sprint 5
Haven't had time to work on it, should be finished this sprint

**Comment by bmvcbr** [comment]
close to being done, going to double check before submission
