### ISSUE TITLE
Investigate macOS issue with running the python server

### ISSUE THREAD

**Issue by bmvcbr** [KSU-SE-2022-TeamPlusPlus/VideoGame#28]

**Comment by vwheatle** [comment]
I tweaked the build instructions to handle a case where the only folder served was the `scripts` folder (the solution was to not have a `scripts` folder) -- maybe this issue was related

**Comment by vwheatle** [comment]
looking into this issue with Ramone, i found a possible answer: https://stackoverflow.com/a/48056064/
so this issue might be caused by running the script with an older version of python 3 (<3.6)

**Comment by Ramone928** [comment]
This issue was resolved because I was using python 2. Note: Add Do not use python 2 warning to readme instructions.
