### ISSUE TITLE
Add Shadows

### ISSUE THREAD

**Issue by jsakal** [KSU-SE-2022-TeamPlusPlus/VideoGame#34]
Add shadows under the player, objects, and enemies.

**Comment by vwheatle** [comment]
the idea is to put shadows below objects to indicate their position in 3d space. the player could use these to determine where to move / jump

beautiful art:

![shadowsAndLanes](https://user-images.githubusercontent.com/98928652/157148013-1e5965b6-402f-4fa4-b2d6-9a05e4d7081e.png)

(caution symbols only for illustration)

**Comment by bmvcbr** [comment]
add shadows to individual art pieces, not a separate object

**Comment by cakhigbe** [comment]
done
